export const FETCH_WHOIS = "FETCH_WHOIS";
export const FETCH_WHOIS_PENDING = "FETCH_WHOIS_PENDING";
export const FETCH_WHOIS_REJECTED = "FETCH_WHOIS_REJECTED";
export const FETCH_WHOIS_FULFILLED = "FETCH_WHOIS_FULFILLED";
